# Generated by Django 4.2.4 on 2023-10-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_orders_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Order Placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_terms',
            field=models.CharField(choices=[('COD', 'COD'), ('Online', 'Online'), ('EMI', 'EMI')], max_length=20),
        ),
    ]
